### ISSUE TITLE
Is it possible to get the rendered fixture temp dir path inside hooks or test modules?

### ISSUE THREAD

**Issue by szevzol** [FabienArcellier/fixtup#29]
It's not a bug rather a question. (if there is a better forum for this kind of questions pls suggest so that I won't open any issues for them later on)

Before my service started up by docker compose, I have to set up a directory structure which will be mounted into the container. I would like to create these directories in the temporary directory of the fixture, before the container starts.

I found that hook_setup_data.py can be a good place for this. But how would that hookl know the temp directory path?

**Comment by FabienArcellier** [comment]
When a fixture is started, the current working directory becore its tmp directory. You can access through `os.gcwd`.

Usually I setup the directory content directly in the fixture directory and set the volume on the containers. That's what is done in [this repository for exemple](https://github.com/FabienArcellier/fixtup/tree/master/tests/fixtures/fixtup). 

The other one is to use the ``hook_setup_data.py`` or the ``hook_started.py``. It's the best way to populate a database : https://fixtup.readthedocs.io/en/latest/handbook.html#populate-a-database-with-data-before-running-a-test

You can use [discord](https://discord.gg/nMn9YPRGSY) to ask question.
